version: "3.9"
services:
    databaseForManagement:
        image: "postgres:14.1"
        mem_limit: 128m
        container_name: "management-database"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: management
            POSTGRES_PASSWORD: management
        healthcheck:
          test: ["CMD-SHELL"]
          interval: 5s
          timeout: 5s
          retries: 6

    databaseForUser:
        image: "postgres:14.1"
        mem_limit: 128m
        container_name: "user-database"
        ports:
            - "5433:5433"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user            
        healthcheck:
            test: ["CMD-SHELL"]
            interval: 5s
            timeout: 5s
            retries: 6

    user:
        build:
          context: ./user-portal
          dockerfile: /src/main/docker/Dockerfile.native
        image: lreimer/hands-on-quarkus:native2
        environment:
          - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5433/user-database
        ports:
          - "8080:8080"  # the HTTP endpoint
        depends_on:
          databaseForUser:
            condition: service_healthy

    zookeeper:
        image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
        container_name: "zookeeper"
        command: [
                "sh", "-c",
                "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs

    kafka:
        image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
        container_name: "kafka"
        command: [
                "sh", "-c",
                "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

